name: deploy

on: [push]

jobs:

    build:
        runs-on: ubuntu-latest

        steps:
            # 切换分支
            - name: Checkout
              uses: actions/checkout@master
            # 下载 git submodule
            - uses: srt32/git-actions@v0.0.3
              with:
                  args: git submodule update --init --recursive
            # 使用 node:10
            - name: use Node.js 10
              uses: actions/setup-node@v1
              with:
                  node-version: 10
            # npm install
            - name: npm install and build
              run: |
                  npm install
              env:
                  CI: true
            - name: Deploy
              uses: easingthemes/ssh-deploy@v2.1.2
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
                  ARGS: "-avz --delete"
                  SOURCE: "dist/"
                  REMOTE_HOST: "118.190.209.112"
                  REMOTE_USER: "root"
                  TARGET: "/home/wwwroot/githubaction"
            - name: Run a command remotely
              uses: docker://evaneos/ssh-action:0.1.0
              with:
                hosts: '118.190.209.112'
                user: 'root'
                private_key: ${{ secrets.ACCESS_TOKEN }}
                commands: pm2 reload rsshub
            #- name: Build
              #run: ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@118.190.209.112 "pm2 stop rsshub"
