name: install_node

on: 
    push:
        branch: 
            - master




jobs:

    build:
        name: build

        runs-on: ubuntu-latest

        steps:
            - name: Set Node.js 12.x
                uses: actions/setup-node@master
                with:
                    node-version: 12.x